trigger: none

pool:
  name: MYJAAN

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/s'
    backendServiceArm: 'Azure subscription 1 (f7d28834-9c52-41d7-adc6-8ae678eef59f)'
    backendAzureRmStorageAccountName: 'shivastgaccount'
    backendAzureRmContainerName: 'shiva_container'
    backendAzureRmKey: 'shiva.tfstate'