# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: MYJAAN

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7' 

